In [4]:
import pandas as pd
import requests
import credentials

In [5]:
#read the input file
df_raw=pd.read_csv('C:/Users/TERRIEAI/OneDrive - KAUST/Files_generated_python/Data_T.csv')

# server
base_URL="http://10.73.58.47/"

In [3]:
df_raw

,Unnamed: 0,Experiment No.,CAS Number,reaction scale (mmol),Equivalent,Property,Volume
0,0,1,824-79-3,0.1,1.0,SM1,NaN
1,1,2,824-79-3,0.1,1.0,SM1,NaN
2,2,3,824-79-3,0.1,1.0,SM1,NaN
3,3,4,824-79-3,0.1,1.0,SM1,NaN
4,4,5,824-79-3,0.1,1.0,SM1,NaN
...,...,...,...,...,...,...,...
171,11,12,127-19-5,0.1,NaN,solvent,1.0
172,12,13,68-12-2,0.1,NaN,solvent,1.0
173,13,14,68-12-2,0.1,NaN,solvent,1.0
174,14,15,68-12-2,0.1,NaN,solvent,1.0
175,15,16,68-12-2,0.1,NaN,solvent,1.0

In [6]:
# Authorization 

URL = base_URL +"cst-api/v1/infrastructure/authorization/login"

headers = {
"accept": "application/json",
"Content-Type": "application/json"
}

Credentials={
  "Credentials": {
    "Username": credentials.username,
    "Password": credentials.password
  }
}


resp = requests.post(URL,headers=headers,json=Credentials)
#tk = json.loads(resp.text)
j=resp.json()
token=j['authorizationContext']['accessToken']

if resp.status_code != 200:
    print('error: ' + str(resp.status_code))
else:
    #print('token: ' + str(token))
    print('Success')

Success

In [5]:
df=df_raw

In [6]:
df['Melting point']=''
df['Molar mass']=''
df['Dispense Tool Volumetric']=''
df['Internal Standard']=''
df['Melting duration']=''
df['Dispensable']=''
df['Density']=''
df=df.fillna('')

In [2]:
#Verify if yhe article is registered

URL_2= base_URL +"/cst-api/v1/product-management/articles/get-articles-by-attributes-values"

headersAPI = {
"accept": "application/json",
'Authorization': 'Bearer '+ token,
}

NameError: name 'base_URL' is not defined

In [7]:

for i in df['CAS Number']:
    if i!='-':
        data= [{"AttributeDefinition": {
        "CstId": "345FAE2E-54E4-4D62-A693-8A8C00A031F8"},
        "Values": [{"String":i}],
        }
        ]

        resp_2 = requests.post(URL_2,headers=headersAPI,json=data,verify=True)

        if resp_2.status_code == 200:
            tk_2=resp_2.json()
            ex=tk_2['result'][0]
            ex_2=ex['attributes']

            index=df[df['CAS Number'].isin([i])].index

            for j in range (0,len(ex_2)-1):
                if ex_2[j]['attributeDefinition']['id'] == 95:
                    df.loc[index,'Melting point']= ex_2[j]['flattenedValue']
                elif ex_2[j]['attributeDefinition']['id'] == 169:
                    df.loc[index,'Molar mass']= ex_2[j]['flattenedValue']
                
                #elif ex_2[i]['attributeDefinition']['id'] == 33:
                #  df['CAS NUMBER']= ex_2[i]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 139:
                    df.loc[index,'Dispense Tool Volumetric']= ex_2[j]['flattenedValue']

                elif ex_2[j]['attributeDefinition']['id'] == 138:
                    df.loc[index,'Dispense Tool Gravimetric']= ex_2[j]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 254:
                    df.loc[index,'Internal Standard']= ex_2[j]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 198:
                    df.loc[index,'Melting duration']= ex_2[j]['flattenedValue']
                
                elif ex_2[j]['attributeDefinition']['id'] == 28:
                    df.loc[index,'Dispensable']= ex_2[j]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 59:
                    df.loc[index,'Density']= ex_2[j]['flattenedValue']
                    
                else:
                    continue
        else:
            pass
    else:
        pass

In [8]:
df

,Unnamed: 0,Experiment No.,CAS Number,reaction scale (mmol),Equivalent,Property,Volume,Dispensable,Dispense Tool Gravimetric,Molar mass,Dispense Tool Volumetric,Density,Melting point
0,0,1,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
1,1,2,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
2,2,3,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
3,3,4,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
4,4,5,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,11,12,127-19-5,0.1,NaN,solvent,1.0,True,NaN,0.08712,4NH,0.943,269.16
172,12,13,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16
173,13,14,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16
174,14,15,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16
175,15,16,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16

In [16]:
# Put the columns in numeric format
df[['Melting duration','Melting point','Molar mass','Density']] = df[['Melting duration','Melting point','Molar mass','Density']].apply(pd.to_numeric)

In [17]:
# Calcul Volume and mass needed for every experiement
df['Volume']=df['Density']*df['Molar mass']*1000*df['scale']*df['Eq']
df['Mass']=df['Molar mass']*1000*df['scale']*df['Eq']

In [18]:
df

,Experiment,Article,CAS Number,scale,Eq,Melting point,Molar mass,Dispense Tool Volumetric,Internal Standard,Melting duration,Dispensable,Density,Dispense Tool Gravimetric,Volume,Mass
0,1,ligand,131833-92-6,0.1,1,298.16,0.26638,,,0.0,,NaN,NaN,NaN,26.638
1,1,Metal Salt,14516-54-2,0.1,1,25.00,0.27489,,,0.0,True,NaN,NaN,NaN,27.489
2,1,Solvent,68-12-2,0.1,1,298.16,0.07309,,,0.0,True,NaN,NaN,NaN,7.309
3,1,S1,71-43-2,0.1,1,315.06,0.07811,,,NaN,,0.879,NaN,6.865869,7.811
4,1,Base,865-47-4,0.1,1,298.16,0.11221,,,0.0,True,NaN,GDU-PFD,NaN,11.221
5,1,Internal standard,108-38-3,0.1,1,298.16,0.10616,4NH,,0.0,True,NaN,NaN,NaN,10.616
6,1,Diluent solvent Filtrate,,0.1,1,NaN,NaN,,,NaN,,NaN,NaN,NaN,NaN
7,1,Diluent Solvent,,0.1,1,NaN,NaN,,,NaN,,NaN,NaN,NaN,NaN
8,2,ligand,133463-88-4,0.1,1,298.16,0.32040,,,0.0,,NaN,NaN,NaN,32.040
9,2,Metal Salt,14516-54-2,0.1,1,25.00,0.27489,,,0.0,True,NaN,NaN,NaN,27.489
10,2,Solvent,68-12-2,0.1,1,298.16,0.07309,,,0.0,True,NaN,NaN,NaN,7.309
11,2,S1,71-43-2,0.1,1,315.06,0.07811,,,NaN,,0.879,NaN,6.865869,7.811
12,2,Base,865-47-4,0.1,1,298.16,0.11221,,,0.0,True,NaN,GDU-PFD,NaN,11.221
13,2,Internal standard,108-38-3,0.1,1,298.16,0.10616,4NH,,0.0,True,NaN,NaN,NaN,10.616
14,2,Diluent solvent Filtrate,,0.1,1,NaN,NaN,,,NaN,,NaN,NaN,NaN,NaN
15,2,Diluent Solvent,,0.1,1,NaN,NaN,,,NaN,,NaN,NaN,NaN,NaN

In [34]:
df.columns

Index(['Experiment', 'Article', 'CAS Number', 'scale', 'Eq', 'Melting point',
       'Molar mass', 'Dispense Tool Volumetric', 'Internal Standard',
       'Melting duration', 'Dispensable', 'Density',
       'Dispense Tool Gravimetric', 'Volume', 'Mass'],
      dtype='object')

In [22]:
index=df[df['CAS Number'].isin(['108-38-3'])].index
df.loc[index,'Internal Standard']

5
13
Name: Internal Standard, dtype: object

In [6]:
#Verify if yhe article is registered

URL_2= base_URL +"/cst-api/v1/product-management/articles/get-articles-by-attributes-values"

headersAPI = {
"accept": "application/json",
'Authorization': 'Bearer '+ token,
}



data= [{"AttributeDefinition": {
        "CstId": "345FAE2E-54E4-4D62-A693-8A8C00A031F8"},
        "Values": [{"String":'108-38-3'}],
        }
        ]

resp_2 = requests.post(URL_2,headers=headersAPI,json=data,verify=True)

resp_2.status_code
tk_2=resp_2.json()
ex=tk_2['result'][0]
ex_2=ex['attributes']

In [7]:
len(ex_2)

7

In [18]:
ex_2[6]['attributeDefinition']['id'] == 254

True

In [ ]:

            index=df[df['CAS Number'].isin([i])].index

            for j in range (0,len(ex_2)-1):
                if ex_2[j]['attributeDefinition']['id'] == 95:
                    df.loc[index,'Melting point']= ex_2[j]['flattenedValue']
                elif ex_2[j]['attributeDefinition']['id'] == 169:
                    df.loc[index,'Molar mass']= ex_2[j]['flattenedValue']
                
                #elif ex_2[i]['attributeDefinition']['id'] == 33:
                #  df['CAS NUMBER']= ex_2[i]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 139:
                    df.loc[index,'Dispense Tool Volumetric']= ex_2[j]['flattenedValue']

                elif ex_2[j]['attributeDefinition']['id'] == 138:
                    df.loc[index,'Dispense Tool Gravimetric']= ex_2[j]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 254:
                    df.loc[index,'Internal Standard']= ex_2[j]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 198:
                    df.loc[index,'Melting duration']= ex_2[j]['flattenedValue']
                
                elif ex_2[j]['attributeDefinition']['id'] == 28:
                    df.loc[index,'Dispensable']= ex_2[j]['flattenedValue']
                    
                elif ex_2[j]['attributeDefinition']['id'] == 59:
                    df.loc[index,'Density']= ex_2[j]['flattenedValue']
                    
                else:
                    continue

In [7]:
def get_att(base_URL,token,data_T):

    URL_2= base_URL +"/cst-api/v1/product-management/articles/get-articles-by-attributes-values"

    headersAPI = {
    "accept": "application/json",
    'Authorization': 'Bearer '+ token,
    }
    
    for i in data_T['CAS Number']:
        if i!='-':
            data= [{"AttributeDefinition": {
            "CstId": "345FAE2E-54E4-4D62-A693-8A8C00A031F8"},
            "Values": [{"String":i}],
            }
            ]

            resp_2 = requests.post(URL_2,headers=headersAPI,json=data,verify=True)

            if resp_2.status_code == 200:
                tk_2=resp_2.json()
                ex=tk_2['result'][0]
                ex_2=ex['attributes']

                index=data_T[data_T['CAS Number'].isin([i])].index

                for j in range (0,len(ex_2)-1):
                    if ex_2[j]['attributeDefinition']['id'] == 95:
                        data_T.loc[index,'Melting point']= ex_2[j]['flattenedValue']
                    elif ex_2[j]['attributeDefinition']['id'] == 169:
                        data_T.loc[index,'Molar mass']= ex_2[j]['flattenedValue']
                    
                    #elif ex_2[i]['attributeDefinition']['id'] == 33:
                    #  data_T['CAS NUMBER']= ex_2[i]['flattenedValue']
                        
                    elif ex_2[j]['attributeDefinition']['id'] == 139:
                        data_T.loc[index,'Dispense Tool Volumetric']= ex_2[j]['flattenedValue']

                    elif ex_2[j]['attributeDefinition']['id'] == 138:
                        data_T.loc[index,'Dispense Tool Gravimetric']= ex_2[j]['flattenedValue']
                        
                    elif ex_2[j]['attributeDefinition']['id'] == 254:
                        data_T.loc[index,'Internal Standard']= ex_2[j]['flattenedValue']
                        
                    
                    elif ex_2[j]['attributeDefinition']['id'] == 28:
                        data_T.loc[index,'Dispensable']= ex_2[j]['flattenedValue']
                        
                    elif ex_2[j]['attributeDefinition']['id'] == 59:
                        data_T.loc[index,'Density']= ex_2[j]['flattenedValue']
                        
                    else:
                        continue
            else:
                pass
        else:
            pass

    return data_T

In [8]:
test=get_att(base_URL,token,df_raw)

In [9]:
test

,Unnamed: 0,Experiment No.,CAS Number,reaction scale (mmol),Equivalent,Property,Volume,Dispensable,Dispense Tool Gravimetric,Molar mass,Dispense Tool Volumetric,Density,Melting point
0,0,1,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
1,1,2,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
2,2,3,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
3,3,4,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
4,4,5,824-79-3,0.1,1.0,SM1,NaN,True,GDU-PFD,0.17819,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,11,12,127-19-5,0.1,NaN,solvent,1.0,True,NaN,0.08712,4NH,0.943,269.16
172,12,13,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16
173,13,14,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16
174,14,15,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16
175,15,16,68-12-2,0.1,NaN,solvent,1.0,True,NaN,0.07309,4NH,0.95,195.16